'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AMainMap

    '''<summary>
    '''style_components control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents style_components As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''style_color control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents style_color As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''ddlEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEMD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtActiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInactiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInactiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInactiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInactiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTotal_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotal_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOnlineCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnlineCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnlineCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnlineCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvJenayah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvJenayah As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtJenayah_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJenayah_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJenayah_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJenayah_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvNarkotik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvNarkotik As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtNarkotik_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNarkotik_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNarkotik_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNarkotik_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvKomersil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvKomersil As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtKomersil_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKomersil_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKomersil_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKomersil_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvCawanganKhas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvCawanganKhas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCawanganKhas_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCawanganKhas_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCawanganKhas_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCawanganKhas_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfAlertID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAlertID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfConfirm As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''plAcknowledge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plAcknowledge As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgPPhoto1Preview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPPhoto1Preview As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtPViolateTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPViolateTerms As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPImei control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPImei As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSubjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSubjectName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSubjectICNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSubjectICNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSubjectContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSubjectContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPoliceStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDepartment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPSContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseerIDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseerIDNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseerContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseerContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPAcknowledgeByID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPAcknowledgeByID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPAcknowledgeDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPAcknowledgeDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPAcknowledge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPAcknowledge As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPCancel As Global.System.Web.UI.WebControls.Button
End Class
