'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AMainMap

    '''<summary>
    '''style_components control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents style_components As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''style_color control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents style_color As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''lbtActiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtActiveEMD As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtActiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtInactiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtInactiveEMD As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtInactiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInactiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInactiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInactiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtTotal_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtTotal_Alert As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''txtTotal_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotal_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOnlineCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnlineCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnlineCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnlineCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtJenayah_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtJenayah_Alert As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''dvJenayah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvJenayah As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtJenayah_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJenayah_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJenayah_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJenayah_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtNarkotik_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtNarkotik_Alert As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''dvNarkotik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvNarkotik As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtNarkotik_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNarkotik_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNarkotik_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNarkotik_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtKomersil_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtKomersil_Alert As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''dvKomersil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvKomersil As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtKomersil_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKomersil_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKomersil_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKomersil_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbtCawanganKhas_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtCawanganKhas_Alert As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''dvCawanganKhas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvCawanganKhas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCawanganKhas_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCawanganKhas_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCawanganKhas_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCawanganKhas_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfAlertID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAlertID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfConfirm As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''rptActiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptActiveEMD As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblActiveEMDListTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveEMDListTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptActiveEMDList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptActiveEMDList As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptInactiveEMDList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptInactiveEMDList As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblViolateTermsTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViolateTermsTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptTotal_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTotal_Alert As Global.System.Web.UI.WebControls.Repeater
End Class
