'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AMainMap

    '''<summary>
    '''style_components control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents style_components As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''style_color control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents style_color As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''ddlEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEMD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtActiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtActiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInactiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInactiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblInactiveEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInactiveEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTotal_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotal_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotal_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOnlineCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnlineCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOnlineCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOnlineCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvJenayah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvJenayah As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtJenayah_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJenayah_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblJenayah_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJenayah_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvNarkotik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvNarkotik As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtNarkotik_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNarkotik_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblNarkotik_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNarkotik_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvKomersil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvKomersil As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtKomersil_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKomersil_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKomersil_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKomersil_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dvCawanganKhas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvCawanganKhas As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtCawanganKhas_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCawanganKhas_Alert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCawanganKhas_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCawanganKhas_Alert As Global.System.Web.UI.WebControls.Label
End Class
