'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AOPPList

    '''<summary>
    '''lblPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''plTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plTable As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSICNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSICNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSICNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSICNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSOrdRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSOrdRefNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSOrdRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSOrdRefNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSDepartment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSDepartment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPoliceStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSPoliceStation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSReset As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTable As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''plUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plUpdate As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPhoto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhoto1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPhoto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoto1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPhoto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPhoto1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPhoto1Validate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhoto1Validate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgPhoto1Preview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPhoto1Preview As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''hfPhoto1Ori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPhoto1Ori As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblPhoto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhoto2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPhoto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoto2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPhoto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPhoto2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPhoto2Validate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhoto2Validate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgPhoto2Preview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPhoto2Preview As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''hfPhoto2Ori control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPhoto2Ori As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblSubjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubjectName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSubjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubjectName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvSubjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSubjectName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblSubjectICNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubjectICNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSubjectICNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubjectICNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvSubjectICNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSubjectICNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblSubjectContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubjectContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSubjectContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubjectContactNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvSubjectContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSubjectContactNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlState As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvState As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDistrict As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDistrict As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDistrict As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblMukim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMukim As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlMukim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMukim As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvMukim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMukim As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPoliceStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPoliceStation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPoliceStation As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepartment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDepartment As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblOffenceDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOffenceDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOffenceDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOffenceDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvOffenceDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOffenceDesc As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblOrderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblActs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblActs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlActs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlActs As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvActs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvActs As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlActsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlActsSection As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvActsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvActsSection As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblOrderIssuedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderIssuedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlOrderIssuedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrderIssuedBy As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvOrderIssuedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOrderIssuedBy As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblOrderIssuedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderIssuedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfOrderIssuedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOrderIssuedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOrderRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderRefNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOrderRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderRefNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvOrderRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOrderRefNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblOrderDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfOrderDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOrderDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOrderPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderPeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOrderPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderPeriod As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlOrderPeriodUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrderPeriodUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''revOrderPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revOrderPeriod As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvOrderPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOrderPeriod As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblReportInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRptPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRptPoliceStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRptPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRptPoliceStation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvRptPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvRptPoliceStation As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblRptPSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRptPSContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRptPSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRptPSContactNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSDNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSDNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvSDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSDNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblOCSName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOCSName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOCSName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOCSName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvOCSName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOCSName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblOCSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOCSContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOCSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOCSContactNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvOCSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOCSContactNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblReportDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportDay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlReportDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportDay As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblReportTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReportTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlReportFrTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportFrTime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlReportToTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlReportToTime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblOversightInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOversightInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRestrictTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRestrictTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRestrictFrTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRestrictFrTime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlRestrictToTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRestrictToTime As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblOthersInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOthersInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemark As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmitOPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitOPP As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnResetOPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetOPP As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBack1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblFileInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAttachment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAttachment1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAttachment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttachment1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAttachment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAttachment1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSubmitAttachment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitAttachment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblAttachment1Validate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAttachment1Validate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptAttachment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptAttachment1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''btnResetFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBack5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack5 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblOverseerInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverseerInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblOverseer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverseer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlOverseer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOverseer As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvOverseer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvOverseer As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblOverseerIDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverseerIDNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOverseerIDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverseerIDNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOverseerIPK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverseerIPK As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOverseerIPK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverseerIPK As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOverseerDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverseerDept As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOverseerDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverseerDept As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblOverseerContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOverseerContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOverseerContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverseerContactNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSubmitOverseer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitOverseer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnResetOverseer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetOverseer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBack2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblGeofenceInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGeofenceInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGeofenceMukim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGeofenceMukim As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlGeofenceMukim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGeofenceMukim As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvGeofenceMukim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvGeofenceMukim As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblGeofenceStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGeofenceStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGeofenceStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGeofenceStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSubmitGeofence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitGeofence As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnResetGeofence control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetGeofence As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnGeofenceStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGeofenceStatus As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBack3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack3 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblEMDDeviceInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMDDeviceInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEMDInstallDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMDInstallDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfEMDInstallDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEMDInstallDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEMD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEMD As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''chkSmartTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSmartTag As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkOBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkOBC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkBeacon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkBeacon As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblBeaconCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBeaconCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBeaconCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBeaconCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkCharger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCharger As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkStrap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStrap As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkCable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCable As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSubmitEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitEMD As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnResetEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetEMD As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnBack4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack4 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''fuPhoto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuPhoto1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''fuPhoto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuPhoto2 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''fuAttachment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuAttachment1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''hfConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfConfirm As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''ValidationSummary2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary2 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''ValidationSummary3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary3 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''ValidationSummary4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary4 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''plVerify control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plVerify As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblPInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPSubject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPPhoto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPhoto1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgPPhoto1Preview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPPhoto1Preview As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblPPhoto2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPhoto2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgPPhoto2Preview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPPhoto2Preview As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblPSubjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPSubjectName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSubjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSubjectName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPSubjectICNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPSubjectICNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSubjectICNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSubjectICNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPSubjectContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPSubjectContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSubjectContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSubjectContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPDistrict As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPDistrict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDistrict As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPMukim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPMukim As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPMukim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPMukim As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPoliceStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPoliceStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPDepartment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDepartment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOffenceDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOffenceDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOffenceDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOffenceDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOrderInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOrderInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPActs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPActs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPActs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPActs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPActsSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPActsSection As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOrderIssuedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOrderIssuedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOrderIssuedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOrderIssuedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOrderIssuedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOrderIssuedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOrderIssuedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOrderIssuedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOrderRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOrderRefNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOrderRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOrderRefNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOrderDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOrderDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOrderDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOrderDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOrderPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOrderPeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOrderPeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOrderPeriod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPReportInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPReportInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPRptPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPRptPoliceStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPRptPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPRptPoliceStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPRptPSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPRptPSContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPRptPSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPRptPSContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPSDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPSDNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSDNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOCSName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOCSName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOCSName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOCSName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOCSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOCSContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOCSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOCSContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPReportDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPReportDay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPReportDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPReportDay As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPReportTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPReportTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPReportFrTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPReportFrTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPReportToTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPReportToTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOverseerInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOverseerInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOverseer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOverseer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOverseerIDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOverseerIDNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseerIDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseerIDNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOverseerIPK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOverseerIPK As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseerIPK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseerIPK As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOverseerDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOverseerDept As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseerDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseerDept As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOverseerContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOverseerContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseerContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseerContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPOversightInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPOversightInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPRestrictTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPRestrictTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPRestrictFrTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPRestrictFrTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPRestrictToTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPRestrictToTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPGeofenceInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPGeofenceInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPGeofenceMukim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPGeofenceMukim As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPGeofenceMukim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPGeofenceMukim As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPEMDDeviceInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPEMDDeviceInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPEMDInstallDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPEMDInstallDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPEMDInstallDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPEMDInstallDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPEMD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkPSmartTag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPSmartTag As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPOBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPOBC As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPBeacon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPBeacon As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblPBeaconCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPBeaconCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPBeaconCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPBeaconCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkPCharger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPCharger As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPStrap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPStrap As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPCable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPCable As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblPFileInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPFileInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPAttachment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPAttachment1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptPAttachment1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPAttachment1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblPRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPRemark As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPApprove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPCancel As Global.System.Web.UI.WebControls.Button
End Class
