'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ATrackingMap

    '''<summary>
    '''style_components control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents style_components As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''style_color control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents style_color As Global.System.Web.UI.HtmlControls.HtmlLink

    '''<summary>
    '''ddlEMD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEMD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''hfOPPID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfOPPID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ddlOPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOPP As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''plOPPInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plOPPInfo As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPhoto As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtOPPName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOPPName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOPPICNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOPPICNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOverseerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverseerName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPoliceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPoliceNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOverseerContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOverseerContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPoliceStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIMEI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIMEI As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgGSMStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGSMStatus As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtGPSStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGPSStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBatteryStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBatteryStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBeltStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBeltStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSpeed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpeed As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfNoResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNoResult As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfAlertID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfAlertID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfConfirm As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''plAcknowledge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plAcknowledge As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''imgPPhoto1Preview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgPPhoto1Preview As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtPViolateTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPViolateTerms As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPImei control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPImei As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSubjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSubjectName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSubjectICNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSubjectICNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPSubjectContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPSubjectContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPoliceStation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPoliceStation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDepartment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPPSContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPPSContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseerIDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseerIDNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPOverseerContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPOverseerContactNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPAcknowledgeByID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPAcknowledgeByID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPAcknowledgeDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPAcknowledgeDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnPAcknowledge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPAcknowledge As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPCancel As Global.System.Web.UI.WebControls.Button
End Class
